[package]
name = "aifc"
version = "0.5.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-codec-algorithms = "0.6.0"

[dev-dependencies]
criterion = { version = "0.5.1" }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
id3 = "1.9.0"

[[bench]]
name = "aifc_benchmark"
harness = false

