[package]
name = "aifc"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio-codec-algorithms = "0.6.0"
no-panic = { version = "0.1", optional = true }

[features]
internal-no-panic = ["dep:no-panic"] # no-panic check is only for testing

[dev-dependencies]
criterion = { version = "0.5.1" }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
id3 = "1.9.0"

[[bench]]
name = "aifc_benchmark"
harness = false

